pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get install -y cmake qtbase5-dev libqt5x11extras5-dev qttools5-dev
          - cmake .
          - ls
          - pwd
  sandbox:
    - step:
        script:
          - ls
          - pwd